apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres
spec:
  #type: NodePort
  ports:
  - name: postgres
    port: 5432
    #nodePort: 30432
  selector:
    app: postgres
